# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alberto Gómez Martín
title: Atención al cliente
email: agomezmartinpro@gmail.com
website: https://agomezmartin1.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  agomezmartin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: albertogomezmartin
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mí
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    He vivido en Londres, Reino Unido once años. Durante estos años realicé mis estudios universitarios (música clásica y traducción) así como el principio de mi carrera profesional.
    Trabajé durante siete años en el departamento de <mark>Eventos Privados</mark> del Museo Británico, y en teatros del West End como parte del equipo de <mark>atención al cliente</mark>.

    Me considero un profesional dinámico que afronta nuevos retos con ilusión y eficacia.
    En la actualidad he decidido dejar atrás mi carrera corporativa para reciclarme y volver a estar en contacto con el cliente me llena de motivación.

content:

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

#    EXPERIENCE

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

  - title: Experiencia laboral # Title for the section
    layout: list # Type of content section (list/text)
    content:

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

      - layout: left
        title: <img src="/images/aldwych.png" width="85%" height="85%">
        link: https://www.nederlander.co.uk/aldwych-theatre
        link_text: aldwych-theatre
        sub_title: Atención al cliente - customer service
        caption: October 2012 - May 2014</br><mark>Londres, Reino Unido</mark> 
#        quote: >

        description: | # this will include new lines to allow paragraphs
            Miembro del equipo de <mark>atención al cliente</mark> del teatro.
              - Recepción de clientes
              - Venta de merchandising
              - Camarero de barra

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

      - layout: left
        title: <img src="/images/doco.png" width="85%" height="85%">
        link: https://www.doco.com/
        link_text: doco.com
        sub_title: Eventos Privados
        caption: October 2007 - May 2012</br><mark>Londres, Reino Unido</mark> 
#        quote: >

        description: | # this will include new lines to allow paragraphs
            Camarero de catering en <mark>eventos corporativos privados</mark> en las salas reservadas del <mark>Museo Británico</mark> de Londres.
              - Montaje de salas
              - Preparación de barras
              - Recepción de invitados

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

      - layout: left
        title: <img src="/images/oratory.png" width="85%" height="85%">
        link: https://www.london-oratory.org/
        link_text: london-oratory.org
        sub_title: Asistente de conversación
        caption: Octubre 2014 - Mayo 2015</br><mark>Londres, Reino Unido</mark> 
#        quote: >

        description: | # this will include new lines to allow paragraphs
            Preparación de exámenes de bachillerato.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

      - layout: left
        title: <img src="/images/gamesys.png" width="85%" height="85%">
        link: https://www.gamesysgroup.com/
        link_text: gamesysgroup.com
        sub_title: Traductor y localizador
        caption: Octubre 2014 - Mayo 2015</br><mark>Londres, Reino Unido</mark> 
#        quote: >

        description: | # this will include new lines to allow paragraphs
            Traducción y localización del video juego online HotShot Trader.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

      - layout: left
        title: <img src="/images/tpt.png" width="85%" height="85%">
        link: https://www.transperfect.com/
        link_text: transperfect.com
        sub_title: Ingeniero de localización
        caption: Madrid, España
        caption: Mayo 2015 - Agosto 2018</br><mark>Madrid, y Barcelona</mark>, España 
#        quote: >

        description: | # this will include new lines to allow paragraphs

          Análisis de contenido y preparación para su correcta traducción a cualquier idioma.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

      - layout: left
        title: <img src="/images/acolad.png" width="85%" height="85%">
        link: https://www.acolad.com/
        link_text: acolad.com
        sub_title: Technical Services Lead | Ingeniero de localizaión
        caption: Septiembre 2018 - Septiembre 2021</br><mark>Madrid, España</mark> 
      #  quote: >

        description: | # this will include new lines to allow paragraphs
          
          Responsable de la totalidad del ciclo de producción de los proyectos de localización.

          <mark>Gestor de prooyectos técnicos</mark>
            - Análisis de requisistos de cliente
            - Creación de presupuestos
            - Redacción de procesos

          <mark>Ingeniería de localización</mark>
            - Preparación de archivos
            - Configuración de herramientas de traducción asistida
            - Creación de recuentos

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

#    EDUCATION

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

  - title: Titulación académica # Title for the section
    layout: list # Type of content section (list/text)
    content:

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

      - layout: left
        title: Imperial College London
        caption: Octubre 2012 - Septiembre 2013</br><mark>Londres, Reino Unido</mark> 
        sub_title: Master en Ciencias de Traducción médica, técnica y científica con tecnología de la traducción
#        quote: >
#          Imperial College London is a world-class university with a mission to benefit society through excellence in science, engineering, medicine and business.
        description: | # this will include new lines to allow paragraphs
          Máster especializado en las tres grandes vertientes técnicas de la traducción y tradumática.

          Gestión de proyectos, traducción asistida por ordenador (TAO).

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

      - layout: left
        title: Imperial College London
        caption: Abril 2013 - Julio 2013</br><mark>Londres, Reino Unido</mark> 
        sub_title: Certificado en Software de Localización
#         quote: >
#           Imperial College London is a world-class university with a mission to benefit society through excellence in science, engineering, medicine and business.
        description: | # this will include new lines to allow paragraphs
          Certificado sobre traducción de software

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

      - layout: left
        title: Universidad de Westeminster
        caption: Septiembre 2009 - Mayo 2012</br><mark>Londres, Reino Unido</mark> 
        sub_title: Grado de Traducción (Español-Inglés)
#        quote: >

        description: | # this will include new lines to allow paragraphs
          Durante este grado desarrollé aptitudes de traducción tanto directa como inversa de inglés y español así como introducción a estudios interculturales e interpretación.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

      - layout: left
        title: Centro de Formación en Tecnologías de la información y las comunicaciones de Madrid
        caption: Mayo 2023 - Julio 2023</br><mark>Madrid, España</mark> 
        sub_title: Visualización y desarrollo de datos con Python (Django y Pandas)
#        quote: >

        description: | # this will include new lines to allow paragraphs
          - Django
          - Python
          - SQL
          - Pandas
#           This <mark>intensive course</mark> dug into the world of data visualization using Python with a focus on <mark>Django</mark> framework.

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

      - layout: left
        title: Core Networks School
        caption: September 2022 - November 2022</br><mark>Madrid, Spain</mark> 
        sub_title: JAVA Enterprise Edition
#        quote: >

        description: | # this will include new lines to allow paragraphs
          Using JAVA Enterprise Edition to develop web-based applications.

          - Java
          - SQL
          - Angular
          - Services

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

  - title: Hobbies
    layout: text
    content: | # this will include new lines to allow paragraphs

      - Inversión financiera
      - Meditación
      - Música

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

# Footer

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

footer_show_references: true
references_title: # References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
